<div class="jumbotron">
    <h1>Gitgram! <small>Postcards From Your Code</small></h1>
    <p>You know you write beautiful code. But does your mom? Your friends? Your boss?</p>
    <h2>Now you can show them.</h2>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Add An Address</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form(null, false)->openTag($this->addressForm);?>
                <?php foreach($this->addressForm as $element): ?>
                    <?php echo $this->formRow($element); ?>
                <?php endforeach; ?>
                <button type="submit" class="btn btn-default">Add to Address Book</button>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>

    <?php echo $this->form(null, false)->openTag($this->createForm);?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Select An Address</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->formRow($this->createForm->get('address')); ?>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create A Gitgram</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->formRow($this->createForm->get('link')); ?>
                <button type="submit" class="btn btn-default">Preview</button>
            </div>
        </div>

        <?php if($this->shipment): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Last Card</h3>
            </div>
            <div class="panel-body">
                    <img src="<?php echo $this->escapeHtml($this->shipment->front) ?>" class="img-thumbnail" style="margin-bottom: 5px">
                    <img src="<?php echo $this->escapeHtml($this->shipment->back) ?>" class="img-thumbnail" style="margin-bottom: 15px">
            </div>
        </div>
        <?php endif; ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>

</div>
